workspace:
  base: /srv/app
  path: src/github.com/owncloud-docker/openshift

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true
    tags: true

pipeline:
  validate:
    image: toolhippie/validjson:latest
    pull: true
    commands:
      - validjson ephemeral.json
      - validjson persistent.json

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    when:
      local: false
      event: [ push, tag ]
      status: [ changed, failure ]
